CREATE TABLE IF NOT EXISTS `form_mental_status` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `form_id` BIGINT(20) NOT NULL,
  `uuid` BINARY(16) DEFAULT NULL,
  `date` DATE DEFAULT NULL,
  `pid` BIGINT(20) DEFAULT NULL,
  `encounter` VARCHAR(255) DEFAULT NULL,
  `user` VARCHAR(255) DEFAULT NULL,
  `groupname` VARCHAR(255) DEFAULT NULL,
  `authorized` TINYINT(4) DEFAULT NULL,
  `activity` TINYINT(4) DEFAULT NULL,

  `appearance` TEXT,
  `attention` VARCHAR(255),
  `concentration` VARCHAR(255),
  `hallucinations` TEXT,
  `delusion` TEXT,
  `memory` TEXT,
  `intelligence` VARCHAR(255),
  `orientation` TEXT,
  `social_judgement` VARCHAR(255),
  `insight` VARCHAR(255),
  `thought_content` TEXT,
  `affect` VARCHAR(255),
  `affect_description` TEXT,
  `mood` VARCHAR(255),
  `mood_description` TEXT,
  `speech` TEXT,
  `behavior` TEXT,
  `thought_disorder` TEXT,
  `sleep` VARCHAR(255),
  `appetite` VARCHAR(255),
  `weight` TEXT,
  `eating_disorders` TEXT,
  `self_harm` TEXT,

  `remarks` TEXT,
  `note_related_to` TEXT,

  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
